services:
  - mysql
language: python
python: "3.6"
before_install:
  - sudo apt-get install python3-dev
  - sudo apt-get install libmysqlclient-dev
  - sudo mysql -e 'CREATE DATABASE cluster;'
  - sudo mysql -e 'CREATE DATABASE cluster_user;'
install: pip install -r requirements.txt
script:
  - pwd
  - ls
  - pytest ./tests